### ISSUE TITLE
Неверно отображается логин

### ISSUE THREAD

**Issue by Nitive** [sea-kg/fhq#118]
![screen shot 2015-05-16 at 14 59 46](https://cloud.githubusercontent.com/assets/6770225/7665515/fa3c15a8-fbd3-11e4-9eed-a92251e3729e.png)

**Comment by Nitive** [comment]
Перелогинился, стало нормально отображаться

**Comment by sea-kg** [comment]
я знаю об этой проблеме ((( потом поправлю... Спасибо )

Best regards
Evgenii Sopov
https://www.facebook.com/eugene.sopov
https://github.com/sea-kg/
other e-mails: sea-kg@ya.ru
skype: sea-kg
icq: 487767371

2015-05-16 15:03 GMT+06:00 Maxim <notifications@github.com>:

**Comment by sea-kg** [comment]
как только будет все переделано на новый механизм сессий эта проблема исчезнет. пока живем с ней.
