### ISSUE TITLE
Не работает авторизация через API

### ISSUE THREAD

**Issue by Nitive** [sea-kg/fhq#119]
```python
email = 'my_emal'
password = 'my_password'

import requests

res = requests.post('http://fhq.keva.su/api/security/login.php?email=' + email + '&password=' + password)
token = res.json()['data']['token']
res2 = requests.post('http://fhq.keva.su/api/games/choose.php?id=5&token=' + token)
print(res2.json())

# output:
{'result': 'fail', 'error': {'message': 'Error 1317: Please relogon', 'code': 1317}, 'data': []}

```

**Comment by sea-kg** [comment]
Да есть такое пока механизм сессий полностью не переделан на токены.
Нужно вызвать  http://fhq.keva.su/api/security/logoff.php

Best regards
Evgenii Sopov
https://www.facebook.com/eugene.sopov
https://github.com/sea-kg/
other e-mails: sea-kg@ya.ru
skype: sea-kg
icq: 487767371

2015-05-16 16:35 GMT+06:00 Maxim <notifications@github.com>:

**Comment by Nitive** [comment]
Так не работает
```python
email = 'my_emal'
password = 'my_password'

import requests

# get old token
oldToken = requests.post('http://fhq.keva.su/api/security/login.php?email=' + email + '&password=' + password).json()['data']['token']

# logout (logoff was not found)
requests.post('http://fhq.keva.su/api/security/logout.php&token=' + oldToken)

# get new token
token = requests.post('http://fhq.keva.su/api/security/login.php?email=' + email + '&password=' + password).json()['data']['token']


print(requests.post('http://fhq.keva.su/api/games/choose.php?id=5&token=' + token).json())

# output:
{'data': [], 'result': 'fail', 'error': {'code': 1317, 'message': 'Error 1317: Please relogon'}}
```

**Comment by sea-kg** [comment]
просто logoff вызови перед logon

Best regards
Evgenii Sopov
https://www.facebook.com/eugene.sopov
https://github.com/sea-kg/
other e-mails: sea-kg@ya.ru
skype: sea-kg
icq: 487767371

2015-05-16 16:46 GMT+06:00 Maxim <notifications@github.com>:

**Comment by Nitive** [comment]
The requested URL `/api/security/logoff.php` was not found on this server.

**Comment by sea-kg** [comment]
Да конечно: api/security/logout.php

	email = 'my_emal'
	password = 'my_password'

	import requests

	# logout
	requests.post('http://fhq.keva.su/api/security/logout.php')

	# get new token
	token = requests.post('http://fhq.keva.su/api/security/login.php?email=' + email + '&password=' + password).json()['data']['token']

	print(requests.post('http://fhq.keva.su/api/games/choose.php?id=5&token=' + token).json())

**Comment by Nitive** [comment]
Все равно `{'error': {'code': 1317, 'message': 'Error 1317: Please relogon'}, 'result': 'fail', 'data': []}`

**Comment by sea-kg** [comment]
как работает на js

	var fhq = new FHQFrontEndLib();
	fhq.client = "web-fhq2014";
	fhq.baseUrl = fhq.getCurrentApiPath(); // or another path

	if (fhq.token && fhq.token != "")  // todo 
		fhq.security.logout();

	function login() {
		var obj = fhq.security.login(this.email.value,this.password.value);
		if (obj.result == "fail") {
			this.error_message.innerHTML = "<b>" + obj.error.message + "</b>";
			this.info_message.innerHTML = "";
		} else {
			window.location.href = "main.php";
		}	
	}

**Comment by sea-kg** [comment]
и попробуй без токенов работать.

**Comment by sea-kg** [comment]
кажется знаю в чем проблема. Вечером поправлю.

**Comment by Nitive** [comment]
Забыл, что есть front-end lib, попробую через нее

**Comment by sea-kg** [comment]
))))) 
	static function userid() {
		// TODO $FHQSESSION
		$userid = (APISecurity::isLogged() && isset($_SESSION['user']['id'])) ? $_SESSION['user']['id'] : '';
		if (intval($userid) == 0) {
			session_destroy();
			APIHelpers::showerror(1317, 'Please relogon');
		}
		return $userid;
	}

**Comment by sea-kg** [comment]
без полноценного тестирования плохо (((

**Comment by Nitive** [comment]
Не работает не первый скрипт, не с logout

**Comment by sea-kg** [comment]
тогда вечером начну писать либу на питоне что бы тестить апи(
17 мая 2015 г. 15:41 пользователь "Maxim" <notifications@github.com>
написал:

**Comment by Nitive** [comment]
Дошло, что данные в post запрос передаю как в get
Исправил, но все равно не помогло
```python
import requests

# get new token
token = requests.post('http://fhq.keva.su/api/security/login.php', {'email': email, 'password': password}).json()['data']['token']
print(token) # token is correct
print(requests.post('http://fhq.keva.su/api/games/choose.php', {'token': token, 'id': 5}).json())
```

**Comment by sea-kg** [comment]
я исправляю сейчас еще ((( там бардак полный мне нужно время + начал писать test.py для бекэнда. могу подготовить виртуалку с девелоп версией. надо? или подождешь пока исправлю все?

**Comment by Nitive** [comment]
Подожду
